---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Will.
--- DateTime: 11/22/2020 9:49 PM
---

function round(num, places)
    local multiplier = 10^(places or 0)
    return math.floor(num * multiplier + 0.5)/multiplier
end