---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Will.
--- DateTime: 11/22/2020 9:50 PM
---

function split(s, delim)
    local result = {}
    if s ~= nil then
        for match in (s..delim):gmatch("(.-)"..delim) do
            table.insert(result, match)
        end
    end
    return result
end