---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Will.
--- DateTime: 11/30/2020 1:14 PM
---

function timedListen(time, port, modem)
    local result = nil
    parallel.waitForAny(function() result = rednetListen(port, modem) end, function() sleep(time) end)
    return result
end


function rednetListen(port, modem)
    modem.open(port)
    local event, modemSide, senderChannel, replyChannel, message, senderDistance = os.pullEvent("modem_message")
    modem.close(port)
    return message
end