---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Will.
--- DateTime: 12/1/2020 6:28 PM
---

function collect()
    turtle.dig()
end

function deploy()
    local wasSuccessful = turtle.place()
    if wasSuccessful then
        turtle.select(2)
        turtle.drop(1)
        turtle.select(1)
        bootTurtle() -- Remotely trigger the turtle to boot
    end
    return wasSuccessful
end

function bootTurtle()
    local computer = peripheral.wrap("front") -- Wrap the front as a peripheral, this will allow us to boot the turtle
    computer.turnOn()
end