---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Will.
--- DateTime: 11/25/2020 16:20 PM
---

os.loadAPI("quarryInventoryManager.lua")

local FUEL_SERVER = 452
local CLIENT = 451

function quarry(width, length, depth)
    -- Quarry from layer yi to yf
    for yi = 1, tonumber(depth) do
        -- Quarry row zi
        for zi = 1, tonumber(length)-1 do
            -- Quarry column xi
            for xi = 1, tonumber(width)-1 do
                -- Check to see if inventory is approaching capacity if so then empty it
                if quarryInventoryManager.getInventoryStatus() > 75 then
                    quarryInventoryManager.emptyInventory()
                end

                -- Check to see if turtle is running low on fuel
                if turtle.getFuelLevel() < 1000 then
                    quarryInventoryManager.refuelTurtle(FUEL_SERVER,CLIENT)
                end

                turtle.dig()
                turtle.forward()
            end

            -- This checks the size of the quarry to see if it is even or odd in length
            -- If even the turtle will turn opposite to that of an odd quarry to keep the layers from shifting
            if length % 2 == 0 and yi % 2 == 0 then
                if zi % 2 == 1 then
                    moveLeft()
                else
                    moveRight()
                end
            else
                if zi % 2 == 1 then
                    moveRight()
                else
                    moveLeft()
                end
            end

        end
        -- Quarry out last column before turning around and starting next layer
        for xi = 1, tonumber(width)-1 do
            turtle.dig()
            turtle.forward()
        end

        turtle.turnLeft()
        turtle.turnLeft()

        -- Check if on final layer before digging down (just an OCD thing to make a clean cube, I'm a programmer sue me)
        if yi < depth then
            turtle.digDown()
            turtle.down()
        end
    end
    quarryInventoryManager.emptyInventory() -- Empty out the inventory one last time
end

function moveLeft()
    turtle.turnLeft()
    turtle.dig()
    turtle.forward()
    turtle.turnLeft()
end

function moveRight()
    turtle.turnRight()
    turtle.dig()
    turtle.forward()
    turtle.turnRight()
end