---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Will.
--- DateTime: 11/26/2020 4:45 PM
---

local INV_LIMIT = 16
local modem = peripheral.wrap("left")

--- Scans the turtle's inventory slots and checks if they contain an item.
--- This function returns the percentage of filled inventory slots
function getInventoryStatus()
    local usedSlots = 0
    for i = 1, INV_LIMIT do
        if turtle.getItemSpace(i) < 64 then
            usedSlots = usedSlots + 1
        end
    end
    return usedSlots/16 * 100
end

-- Triggers the turtle docking station to refuel the turtle while the fuel level is less than 19500 (max 20000)
function refuelTurtle(server,client)
    while turtle.getFuelLevel() < 1000 do
        parallel.waitForAll(function() refuel() end, function() requestFuel(server,client) end)
    end
    emptyInventory()
end

function refuel()
    turtle.placeUp() -- Place Ender Chest
    if getInventoryStatus() > 75 then
        emptyInventory()
        turtle.placeUp()
    end

    turtle.suckUp()
    local idx = getFuelIndex()
    if idx ~= nil then
        turtle.select(idx)
        turtle.refuel()
    end
    return
end

function requestFuel(server,client)
    modem.transmit(server,client,"REFUEL")
    return
end

function getFuelIndex()
    for i=1, INV_LIMIT do
        turtle.select(i)
        local itemData = turtle.getItemDetail()
        if itemData ~= nil then
            if itemData.name == "minecraft:lava_bucket" then
                turtle.select(1)
                return i
            end
        end
    end
end


-- Cycle through all slots in the inventory and empty the slots of items
function emptyInventory()
    turtle.placeUp()
    for i = 1, INV_LIMIT do
        turtle.select(i)
        local itemCount = turtle.getItemCount()
        turtle.dropUp(itemCount)
    end
    turtle.select(1)
    turtle.digUp() -- Recollect Ender Chest
end